[package]
name = "vortex_sync"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
arrow-array = "*"
envy = "0.4"
object_store = { version= "0.12.1", features = ["aws", "azure", "serde"] }
serde = "1.0"
tokio = { version = "1.45", features = ["full"] }
url = { version = "2.5", features = ["serde"] }
vortex = { version = "0.34.0", features = ["tokio", "object_store", "parquet"] }
